# Generated by Django 4.1 on 2022-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('Nur', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI')], max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_qualification', models.CharField(max_length=100)),
                ('mother_qualification', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('father_designation', models.CharField(max_length=100)),
                ('mother_designation', models.CharField(max_length=100)),
                ('father_organisation', models.CharField(max_length=150)),
                ('mother_organisation', models.CharField(max_length=150)),
                ('father_mobile', models.CharField(max_length=10)),
                ('mother_mobile', models.CharField(max_length=10)),
                ('father_email', models.EmailField(max_length=100)),
                ('mother_email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
